### ISSUE TITLE
Error while receiving referral from m.me link

### ISSUE THREAD

**Issue by maxtomczyk** [chatbots-pl/powerbot-messenger#4]
```
  TypeError: Cannot read property 'quick_reply' of undefined
      at router.post (/Users/max/Projects/powerbot-based-project/node_modules/@chatbots-pl/powerbot/node_modules/@chatbots-pl/powerbot-messenger/models/Server.js:89:42)
      at dispatch (/Users/max/Projects/powerbot-based-project/node_modules/@chatbots-pl/powerbot/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
      at next (/Users/max/Projects/powerbot-based-project/node_modules/@chatbots-pl/powerbot/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
      at /Users/max/Projects/powerbot-based-project/node_modules/@chatbots-pl/powerbot/node_modules/koa-router/lib/router.js:346:16
      at dispatch (/Users/max/Projects/powerbot-based-project/node_modules/@chatbots-pl/powerbot/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
      at /Users/max/Projects/powerbot-based-project/node_modules/@chatbots-pl/powerbot/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
      at dispatch (/Users/max/Projects/powerbot-based-project/node_modules/@chatbots-pl/powerbot/node_modules/koa-router/lib/router.js:351:31)
      at dispatch (/Users/max/Projects/powerbot-based-project/node_modules/@chatbots-pl/powerbot/node_modules/koa-compose/index.js:42:32)
      at bodyParser (/Users/max/Projects/powerbot-based-project/node_modules/@chatbots-pl/powerbot/node_modules/koa-bodyparser/index.js:86:11)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by maxtomczyk** [comment]
Fixed in v1.0.3
